version: "3.9"

services:

  # ======================
  # DATABASE
  # ======================
  db:
    image: postgres:16
    container_name: barber_db
    restart: always
    environment:
      POSTGRES_DB: barber_tech
      POSTGRES_USER: barber_user
      POSTGRES_PASSWORD: Barber_pass_123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # ======================
  # BACKEND (DJANGO)
  # ======================
  backend:
    build: ./Barber_Tech_Backend
    container_name: barber_backend
    volumes:
      - ./Barber_Tech_Backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./Barber_Tech_Backend/.env
    depends_on:
      - db
    command: >
      sh -c "
      echo 'Waiting for postgres...' &&
      sleep 10 &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "

  # ======================
  # FRONTEND (REACT)
  # ======================
  frontend:
    build: ./Barber_Tech_Frontend
    container_name: barber_frontend
    volumes:
      - ./Barber_Tech_Frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://backend:8000/api/
    depends_on:
      - backend

# ======================
# VOLUMES
# ======================
volumes:
  postgres_data:
